### PR TITLE
index.d.ts for TypeScript support

### LINKED ISSUE #7: TypeScript support
Doesn't work with TS

```
import RemoveEmptyScriptsPlugin from 'webpack-remove-empty-scripts';
```

> TS7016: Could not find a declaration file for module 'webpack-remove-empty-scripts'. '.../node_modules/webpack-remove-empty-scripts/src/index.js' implicitly has an 'any' type.

### PR DESCRIPTION
**Pull request by lmcsu**
Closes #7

### CODE REVIEW

**Comment by webdiscus** [comment]
@lmcsu 
Thank you for the help!
In few hours I release new version in npm repo.

**Comment by webdiscus** [comment]
@lmcsu 
the new version `0.8.1` is released

**Comment by G-Rath** [comment]
Note that these types are slightly incorrect - I have opened #13 fixing them

**Comment by webdiscus** [comment]
@G-Rath 

thank you! Your fix is merged and published with new version `1.0.2`.

**Pull request merged**
